from langchain.chat_models import ChatOpenAI
from langchain.prompts import ChatPromptTemplate
class FriendlinessDetector:
    def __init__(self):
        self.chat = ChatOpenAI(temperature=0.0)
        self.template_string = """There's now a sentence from daily conversations generated by a language model.\n
        Your task is: Judge whether the tone between the participants is friendly,
        meaning it doesn't provoke extreme emotions. You need to answer with friendly/unfriendly.\n
        ---------------\n
        Here are some examples, please learn to discern the boundaries and details.\n
        example1\n
        sentence: Well, it's not my problem if you can't handle your own mess.\n
        judgement: unfriendly\n
        example2\n
        sentence: I thoroughly enjoy reading; it's an escape to different worlds for me.\n
        judgement: friendly\n
        example3\n
        sentence: Honestly, I wish you could be a bit more considerate.\n
        judgement: unfriendly\n
        example4\n
        sentence: This park is beautiful; I love how peaceful it is in the mornings.\n
        judgement: friendly\n
        example5\n
        sentence: If you were as good at working as you are at talking, we'd be done by now.\n
        judgement: unfriendly\n
        example6\n
        sentence: I appreciate your help; it really made a difference in my project.\n
        judgement: friendly\n
        example7\n
        sentence: Why don't you mind your own business instead of meddling in mine?\n
        judgement: unfriendly\n
        example8\n
        sentence: I've been into astronomy lately; the vastness of space is simply fascinating.\n
        judgement: friendly\n
        ---------------\n
        sentence: {query_str}
        judgement: 
        """

        self.prompt_template = ChatPromptTemplate.from_template(self.template_string)

    def generate_response(self, query_str):
        messages = self.prompt_template.format_messages(query_str=query_str)
        response = self.chat(messages)
        return response.content

