from langchain.chat_models import ChatOpenAI
from langchain.prompts import ChatPromptTemplate
class TopicTransitionDetector:
    def __init__(self):
        self.chat = ChatOpenAI(temperature=0.0)
        self.template_string = """Now there's a piece of daily spoken dialogue between two people and a sentence
        generated by a language model based on this context.\n
        Your task is: Based on this conversation, determine whether the idea conveyed by this reply is to continue the 
        conversation rather than to end the topic. You need to answer yes/no, representing wanting to continue the 
        conversation/not wanting to continue the conversation.\n
        ---------------\n
        example1\n
        context: "What's your favorite type of cuisine?", "I love Italian food.", "Oh, me too! I just can't get enough of pasta.", "What's your favorite Italian dish?"
        sentence: "Well, I'm really not that into food. I just eat whatever's there."
        answer: no
        example2\n
        context: "Have you seen the latest episode of that show?", "No, I haven't had the time.", "You should, it's quite a twist!", "I'll make sure to catch up on it."
        sentence: "Yes, you should! Can't wait to discuss it with you."
        answer: yes
        example3\n
        context: "Are you free this weekend?", "I'm not sure yet, why do you ask?", "I was thinking we could go hiking.", "That sounds nice, but I need to check my schedule."
        sentence: "Well, I'm not much of an outdoors person, so I'll probably pass."
        answer: no
        example4\n
        context: "I recently started learning a new language.", "Oh, that's interesting, which one?", "I'm trying to learn Spanish.", "That's cool! I've heard it's a beautiful language.", "Yes, it is. Have you ever thought of learning a new language?"
        sentence: "Yes, in fact, I've always wanted to learn Spanish too! Maybe we can study together."
        answer: yes
        example5\n
        context: "Did you catch the game last night?", "No, I missed it. How did it go?", "Our team won, it was a really exciting match!", "That's great, I'll watch the replay tonight."
        sentence: "Cool, I'll look forward to hearing what you think."
        answer: yes
        example6\n
        context: "Have you heard the new album by that band?", "No, not yet. Is it good?", "Yeah, it's amazing! You should listen to it.", "I'll check it out when I have the time."
        sentence: "Well, if you ever get a chance, let me know your thoughts."
        answer: yes
        example7\n
        context: "Are you planning to attend the event this weekend?", "I'm not sure, I have a lot of work.", "It would be fun, you should come.", "I'll think about it."
        sentence: "Sure, whatever floats your boat."
        answer: no
        example8\n
        context: "Have you visited the new art exhibition downtown?", "Not yet, but I'm planning to.", "It's fantastic! You'll love it.", "I hope so, I'm looking forward to it."
        sentence: "Hmm, if you say so."
        answer: no
        ---------------\n
        context: {context}
        sentence: {query_str}
        answer: 
        """
        self.prompt_template = ChatPromptTemplate.from_template(self.template_string)

    def generate_response(self, query_str, context):
        messages = self.prompt_template.format_messages(query_str=query_str,context=context)
        response = self.chat(messages)
        return response.content

